// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SynergyDistrict.Server.Data;

#nullable disable

namespace SynergyDistrict.Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251209183450_SynergyModelFix01")]
    partial class SynergyModelFix01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("SynergyDistrict.Server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.BuildingProduction", b =>
                {
                    b.Property<int>("BuildingProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingSynergyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingProductionId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingSynergyId");

                    b.ToTable("BuildingProductions");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.BuildingSynergy", b =>
                {
                    b.Property<int>("BuildingSynergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceBuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetBuildingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingSynergyId");

                    b.HasIndex("SourceBuildingId");

                    b.HasIndex("TargetBuildingId");

                    b.ToTable("BuildingSynergies");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.BuildingProduction", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.Building", "Building")
                        .WithMany("BaseProduction")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SynergyDistrict.Server.Models.BuildingSynergy", null)
                        .WithMany("SynergyProductions")
                        .HasForeignKey("BuildingSynergyId");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.BuildingSynergy", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.Building", "SourceBuilding")
                        .WithMany("OutgoingSynergies")
                        .HasForeignKey("SourceBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SynergyDistrict.Server.Models.Building", "TargetBuilding")
                        .WithMany("IncomingSynergies")
                        .HasForeignKey("TargetBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceBuilding");

                    b.Navigation("TargetBuilding");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Building", b =>
                {
                    b.Navigation("BaseProduction");

                    b.Navigation("IncomingSynergies");

                    b.Navigation("OutgoingSynergies");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.BuildingSynergy", b =>
                {
                    b.Navigation("SynergyProductions");
                });
#pragma warning restore 612, 618
        }
    }
}
