// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SynergyDistrict.Server.Data;

#nullable disable

namespace SynergyDistrict.Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260207180312_small")]
    partial class small
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SynergyItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.HasIndex("SynergyItemId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingProduction", b =>
                {
                    b.Property<int>("BuildingProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingSynergyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingUpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingProductionId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingSynergyId");

                    b.HasIndex("BuildingUpgradeId");

                    b.ToTable("BuildingProductions");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingUpgrade", b =>
                {
                    b.Property<int>("BuildingUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeleteCost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpgradeCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingUpgradeId");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingUpgrades");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Synergy", b =>
                {
                    b.Property<int>("SynergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingUpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSynergyItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSynergyItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SynergyId");

                    b.HasIndex("BuildingUpgradeId");

                    b.HasIndex("SourceSynergyItemId");

                    b.HasIndex("TargetSynergyItemId");

                    b.ToTable("BuildingSynergies");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.SynergyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SynergyItems");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Building", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.SynergyItem", "SynergyItem")
                        .WithMany()
                        .HasForeignKey("SynergyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SynergyItem");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingProduction", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.Buildings.Building", "Building")
                        .WithMany("BaseProduction")
                        .HasForeignKey("BuildingId");

                    b.HasOne("SynergyDistrict.Server.Models.Buildings.Synergy", "BuildingSynergy")
                        .WithMany("SynergyProductions")
                        .HasForeignKey("BuildingSynergyId");

                    b.HasOne("SynergyDistrict.Server.Models.Buildings.BuildingUpgrade", null)
                        .WithMany("UpgradeProductions")
                        .HasForeignKey("BuildingUpgradeId");

                    b.Navigation("Building");

                    b.Navigation("BuildingSynergy");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingUpgrade", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.Buildings.Building", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Synergy", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.Buildings.BuildingUpgrade", null)
                        .WithMany("UpgradeSynergies")
                        .HasForeignKey("BuildingUpgradeId");

                    b.HasOne("SynergyDistrict.Server.Models.SynergyItem", "SourceSynergyItem")
                        .WithMany()
                        .HasForeignKey("SourceSynergyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SynergyDistrict.Server.Models.SynergyItem", "TargetSynergyItem")
                        .WithMany()
                        .HasForeignKey("TargetSynergyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSynergyItem");

                    b.Navigation("TargetSynergyItem");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Building", b =>
                {
                    b.Navigation("BaseProduction");

                    b.Navigation("Upgrades");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingUpgrade", b =>
                {
                    b.Navigation("UpgradeProductions");

                    b.Navigation("UpgradeSynergies");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Synergy", b =>
                {
                    b.Navigation("SynergyProductions");
                });
#pragma warning restore 612, 618
        }
    }
}
