// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SynergyDistrict.Server.Data;

#nullable disable

namespace SynergyDistrict.Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260104104043_hotfix01")]
    partial class hotfix01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Cost = 50,
                            Description = "Automated logging unit. Harvests resources from nearby woodlands. Warning: High decibel output affects residential zones.",
                            IconKey = "lumberjack",
                            Name = "Lumberjack",
                            ShapeSerialized = "[[1,2,0],[0,1,1]]",
                            Type = 3
                        },
                        new
                        {
                            BuildingId = 2,
                            Cost = 500,
                            Description = "Deep-crust drilling operation. Maximizes raw material output. Causes severe happiness penalty in the immediate vicinity.",
                            IconKey = "mine",
                            Name = "Mine",
                            ShapeSerialized = "[[1,2],[0,1]]",
                            Type = 3
                        },
                        new
                        {
                            BuildingId = 3,
                            Cost = 200,
                            Description = "Sustainable agricultural zone. Essential for maintaining workforce levels. Benefits from adjacency to other farming units.",
                            IconKey = "farm",
                            Name = "Farm",
                            ShapeSerialized = "[[0,2,1],[1,1,1]]",
                            Type = 3
                        },
                        new
                        {
                            BuildingId = 4,
                            Cost = 800,
                            Description = "Processing facility for raw materials. Generates significant economic value but emits pollutants. Requires stable power connection.",
                            IconKey = "factory",
                            Name = "Factory",
                            ShapeSerialized = "[[1,2,1,1]]",
                            Type = 2
                        },
                        new
                        {
                            BuildingId = 5,
                            Cost = 100,
                            Description = "Standard living quarters for the workforce. Tax revenue scales dynamically with the satisfaction level of tenants.",
                            IconKey = "house",
                            Name = "House",
                            ShapeSerialized = "[[1,2,1],[0,1,0]]",
                            Type = 0
                        },
                        new
                        {
                            BuildingId = 6,
                            Cost = 300,
                            Description = "Designated recreational area. Counteracts the negative psychological effects of industrialization. Requires daily upkeep.",
                            IconKey = "park",
                            Name = "Park",
                            ShapeSerialized = "[[1,1,2],[0,0,1]]",
                            Type = 4
                        },
                        new
                        {
                            BuildingId = 7,
                            Cost = 0,
                            Description = "Administrative center of Synergy District. Coordinates city-wide efficiency and provides the initial power grid setup.",
                            IconKey = "townhall",
                            Name = "Town Hall",
                            ShapeSerialized = "[[2,1],[1,1]]",
                            Type = 1
                        },
                        new
                        {
                            BuildingId = 8,
                            Cost = 150,
                            Description = "Small-scale commercial outlet. Provides goods for local residents. Operational only when placed near populated areas.",
                            IconKey = "shop",
                            Name = "Market",
                            ShapeSerialized = "[[0,1,1],[1,2,0]]",
                            Type = 1
                        });
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingProduction", b =>
                {
                    b.Property<int>("BuildingProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingSynergyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingProductionId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingSynergyId");

                    b.ToTable("BuildingProductions");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingSynergy", b =>
                {
                    b.Property<int>("BuildingSynergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceBuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetBuildingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingSynergyId");

                    b.HasIndex("SourceBuildingId");

                    b.HasIndex("TargetBuildingId");

                    b.ToTable("BuildingSynergies");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingProduction", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.Buildings.Building", "Building")
                        .WithMany("BaseProduction")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SynergyDistrict.Server.Models.Buildings.BuildingSynergy", null)
                        .WithMany("SynergyProductions")
                        .HasForeignKey("BuildingSynergyId");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingSynergy", b =>
                {
                    b.HasOne("SynergyDistrict.Server.Models.Buildings.Building", "SourceBuilding")
                        .WithMany("OutgoingSynergies")
                        .HasForeignKey("SourceBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SynergyDistrict.Server.Models.Buildings.Building", "TargetBuilding")
                        .WithMany("IncomingSynergies")
                        .HasForeignKey("TargetBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceBuilding");

                    b.Navigation("TargetBuilding");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.Building", b =>
                {
                    b.Navigation("BaseProduction");

                    b.Navigation("IncomingSynergies");

                    b.Navigation("OutgoingSynergies");
                });

            modelBuilder.Entity("SynergyDistrict.Server.Models.Buildings.BuildingSynergy", b =>
                {
                    b.Navigation("SynergyProductions");
                });
#pragma warning restore 612, 618
        }
    }
}
